export const ApiEndpoint = {
  REFRESH_TOKEN: '/refresh-token',
  LOGIN: '/mobile/login',
  LOGOUT: '/mobile/logout',
  MOBILE_LOGIN: '/mobile/login',
  PRODUCTS: '/products/json',
  CUSTOMERS: '/customers',
  EMPLOYEES: '/api/employees',
  ORDERS_API: '/api/orders',
  ORDERS: '/orders',
  CUSTOMERS_PUBLIC: '/customers/json',
  PROMOTIONS: '/promotions/api/json',
  PROVIDERS: '/providers',
  WARRANTY: '/warranty-support/json',
};
